package Vista;

import Conecxion.Conecxion;
import Controlador.Ctrl_Categoria;
import Modelo.Categoria;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.awt.event.MouseAdapter;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author caren
 */
public class InterGestionarCategorias extends javax.swing.JInternalFrame {

    private int idCategoria;

    public InterGestionarCategorias() {
        initComponents();
        this.setSize(600, 400);
        this.setTitle("Gestionar Categorias");
        this.CargarTablaCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_categorias = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1_actualiza = new javax.swing.JButton();
        jButton2_eliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        jLabel1_walper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Categorias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_categorias.setBackground(new java.awt.Color(30, 30, 30));
        jTable_categorias.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable_categorias.setForeground(new java.awt.Color(0, 0, 0));
        jTable_categorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_categorias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 350, 250));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1_actualiza.setBackground(new java.awt.Color(85, 239, 196));
        jButton1_actualiza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1_actualiza.setForeground(new java.awt.Color(0, 0, 0));
        jButton1_actualiza.setText("Actualizar");
        jButton1_actualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_actualizaActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1_actualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jButton2_eliminar.setBackground(new java.awt.Color(250, 177, 160));
        jButton2_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        jButton2_eliminar.setText("Eliminar");
        jButton2_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 130, 90));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Descripcion:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));
        jPanel4.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 190, 80));

        jLabel1_walper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel1_walper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_eliminarActionPerformed
        if (!txt_descripcion.getText().isEmpty()) {
            Categoria categoria = new Categoria();
            Ctrl_Categoria controlCategoria = new Ctrl_Categoria();

            categoria.setDescripcion(txt_descripcion.getText().trim());
            if (controlCategoria.eliminar(idCategoria)) {
                JOptionPane.showConfirmDialog(null, "Categoria actializad");
                txt_descripcion.setText("");
                this.CargarTablaCategoria();
            } else {
                JOptionPane.showConfirmDialog(null, "error al eliminar categoria");
            }
        } else {
            JOptionPane.showConfirmDialog(null, "seleccione una categoria");
        }

    }//GEN-LAST:event_jButton2_eliminarActionPerformed

    private void jButton1_actualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_actualizaActionPerformed
        if (!txt_descripcion.getText().isEmpty()) {
            Categoria categoria = new Categoria();
            Ctrl_Categoria controlCategoria = new Ctrl_Categoria();

            categoria.setDescripcion(txt_descripcion.getText().trim());
            if (!controlCategoria.actualizar(categoria, idCategoria)) {
                JOptionPane.showConfirmDialog(null, "Categoria actializad");
                txt_descripcion.setText("");
                this.CargarTablaCategoria();
            } else {
                JOptionPane.showConfirmDialog(null, "error al actualiza categoria");
            }
        } else {
            JOptionPane.showConfirmDialog(null, "seleccione una categoria");
        }

    }//GEN-LAST:event_jButton1_actualizaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_actualiza;
    private javax.swing.JButton jButton2_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_walper;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_categorias;
    private javax.swing.JTextField txt_descripcion;
    // End of variables declaration//GEN-END:variables

    //mostrar todas las categorias
    private void CargarTablaCategoria() {
        Connection con = (Connection) Conecxion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select idCategoria, descripcion,estado from tb_categoria";
        Statement st;
        try {
            st = (Statement) con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            InterGestionarCategorias.jTable_categorias = new JTable(model);
            InterGestionarCategorias.jScrollPane1.setViewportView(InterGestionarCategorias.jTable_categorias);

            model.addColumn("idCategoria");
            model.addColumn("descripcion");
            model.addColumn("estado");
            while (rs.next()) {
                Object fila[] = new Object[3];
                for (int i = 0; i < 3; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            con.close();

        } catch (SQLException e) {
            System.out.println("erros al llenar tabla" + e);
        }
        jTable_categorias.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_categorias.rowAtPoint(e.getPoint());
                int columna_point = 0;
                if (fila_point > -1) {
                    idCategoria = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosCategoriaSelecinada(idCategoria);
                }
            }
        });
        {

        }

    }

    private void EnviarDatosCategoriaSelecinada(int idCategoria) {
        try {
            try (Connection con = (Connection) Conecxion.conectar()) {
                PreparedStatement pst = (PreparedStatement) con.prepareStatement("select* from tb_categoria=" + idCategoria + "");
                ResultSet rs = pst.executeQuery();
                
                if (rs.next()) {
                    txt_descripcion.setText(rs.getString("descripcion"));
                }
            }
        } catch (SQLException e) {
            System.out.println("error al cargaar categori" + e);
        }
    }

}
